import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Box, Button, Container, Text } from "@chakra-ui/react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Pemilu 8EH</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container width="100vw">
        <Box width={"100vw"}>
          <Text fontSize={"5xl"}>Welcome to Pemilu 8EH.</Text>
        </Box>
        <Box justifyContent={"center"}>
          <Link href="/login">
          <Button variant="solid" colorScheme="teal">
            Login
          </Button>
          
          </Link>
        </Box>
      </Container>
    </>
  );
}
